german token translation complete
zzorba/arkham-cards-data pull request #485
Opened 2021-10-15 10:26 UTC by comlah

2021-10-15 10:33 UTC, tjanu requested changes

2021-10-15 10:33 UTC, tjanu commented on i18n/de/chaos_tokens.po
> +msgstr "Anzahl der enthüllter Verwunschener Wald-Orte."
"Anzahl der enthüllten"

2021-10-15 10:33 UTC, tjanu commented on i18n/de/chaos_tokens.po
> +msgstr "Anzahl an Schlüssel, welchen die Ermittler kontrollieren, plus 1"
Anzahl an Schlüsseln

2021-10-16 18:52 UTC, merged

2021-10-16 18:53 UTC, zzorba commented
Will make these corrections manually @tjanu after merging.