Update ko translations
zzorba/arkham-cards-data pull request #807
Opened 2022-08-29 06:33 UTC by derornos

- atw, faq 2.0, errata, ...

2022-08-29 06:35 UTC, derornos commented
Hi, zzorba!

How to update ko translations for 'Rules and Clarification (1.23–1.26, 2.13–2.23)'?

2022-08-29 13:51 UTC, elkeinkrad commented
* I have a plan to apply the errata of the **player** card into ArkhamDB, so that you do not need to add in this, I think. Additionally, it seems that this errata only covers the encounter part. In my opinion, the player card of the errata is not necessory, and may be removed?.
 * Instead of the copy and paste from the reference, please paraphrase them to focus on the change only. It is because the reference also write the "reason" of the errata, but this errata only focus on the change point. I'll write a comment via the review.

2022-08-29 14:01 UTC, elkeinkrad requested changes

2022-08-29 14:01 UTC, elkeinkrad commented on errata/ko/errata.json
> +          "text": "카르코사로 가는 길의 개정판에서 특성 명칭이 [[광인]]에서 [[홀린]]으로 수정되었습니다. 또한 카드 명칭이 아래와 같이 수정되어야 합니다.\n기존 문구: [미치광이](card/03095)\n개정 문구: [표식을 목도한 자](card/03095)"
본 카드의 명칭은 "표식을 목도한 자"로 수정해야 합니다. 본 카드의 "[[광인]]" 특성은 "[[홀린]]" 특성으로 수정해야 합니다.

2022-08-29 14:01 UTC, elkeinkrad commented on errata/ko/errata.json
> +          "text": "카르코사로 가는 길의 개정판에서 특성 명칭이 [[광인]]에서 [[홀린]]으로 수정되었습니다. 또한 카드 명칭이 아래와 같이 수정되어야 합니다.\n기존 문구: [젊은 싸이코패스](card/03095)\n개정 문구: [하스터의 꼭두각시](card/03095)"
본 카드의 명칭은 "하스터의 꼭두각시"로 수정해야 합니다. 본 카드의 "[[광인]]" 특성은 "[[홀린]]" 특성으로 수정해야 합니다.

2022-08-29 14:01 UTC, elkeinkrad commented on errata/ko/errata.json
> +          "text": "카르코사로 가는 길의 개정판에서 특성 명칭이 [[광인]]에서 [[홀린]]으로 수정되었습니다."
본 카드의 "[[광인]]" 특성은 "[[홀린]]" 특성으로 수정해야 합니다.

2022-08-29 14:01 UTC, elkeinkrad commented on errata/ko/errata.json
> +          "text": "카르코사로 가는 길의 개정판에서 특성 명칭이 [[광인]]에서 [[홀린]]으로 수정되었습니다."
본 카드의 "[[광인]]" 특성은 "[[홀린]]" 특성으로 수정해야 합니다.

2022-08-29 14:01 UTC, elkeinkrad commented on errata/ko/errata.json
> +          "text": "카르코사로 가는 길의 개정판에서 특성 명칭이 [[광인]]에서 [[홀린]]으로 수정되었습니다. 또한 카드 명칭이 아래와 같이 수정되어야 합니다.\n기존 문구: [미친 환자](card/03184)\n개정 문구: [신들린 환자](card/03184)"
본 카드의 명칭은 "신들린 환자"로 수정해야 합니다. 본 카드의 "[[광인]]" 특성은 "[[홀린]]" 특성으로 수정해야 합니다.

2022-08-29 14:01 UTC, elkeinkrad commented on errata/ko/errata.json
> +          "text": "기존 문구: <b>강제</b> – ‘버질 그레이’가 '쓰러지면': ‘버질 그레이’를 게임에서 제거합니다.\n개정 문구: <b>강제</b> – ‘버질 그레이’가 '플레이 영역에서 나가면': ‘버질 그레이’를 게임에서 제거합니다."
<b>강제</b> 기능의 전제 조건이 다음과 같이 수정되어야 합니다: ‘버질 그레이’가 플레이 영역에서 나가면

2022-08-29 14:01 UTC, elkeinkrad commented on errata/ko/errata.json
> +          "text": "기존 문구: <b>강제</b> – ‘버질 그레이’가 '쓰러지면': ‘버질 그레이’를 게임에서 제거합니다.\n개정 문구: <b>강제</b> – ‘버질 그레이’가 '플레이 영역에서 나가면': ‘버질 그레이’를 게임에서 제거합니다."
<b>강제</b> 기능의 전제 조건이 다음과 같이 수정되어야 합니다: ‘버질 그레이’가 플레이 영역에서 나가면

2022-08-29 14:01 UTC, elkeinkrad commented on errata/ko/errata.json
> +          "text": "기존 문구: <b>강제</b> – '라운드 끝에', ‘데이곤의 침소’에 조사자가 있고 ‘데이곤’이 준비 상태라면: 이 적에게 파멸을 1개 놓습니다.\n개정 문구: <b>강제</b> – '조사 단계 끝에', ‘데이곤의 침소’에 조사자가 있고 ‘데이곤’이 준비 상태라면: 이 적에게 파멸을 1개 놓습니다."
<b>강제</b> 기능의 전제 조건이 다음과 같이 수정되어야 합니다: 조사 단계 끝에...

2022-08-29 14:01 UTC, elkeinkrad commented on errata/ko/errata.json
> +          "text": "기존 문구: <b>강제</b> – '라운드 끝에', ‘하이드라의 침소’에 조사자가 있고 ‘하이드라’가 준비 상태라면: 이 적에게 파멸을 1개 놓습니다.\n개정 문구: <b>강제</b> – '조사 단계 끝에', ‘하이드라의 침소’에 조사자가 있고 ‘하이드라’가 준비 상태라면: 이 적에게 파멸을 1개 놓습니다."
<b>강제</b> 기능의 전제 조건이 다음과 같이 수정되어야 합니다: 조사 단계 끝에...

2022-08-29 14:01 UTC, elkeinkrad commented on errata/ko/errata.json
> +          "text": "기존 문구: <b>강제</b> - 당신이 부착된 장소에서 '나갈 때': 그 장소의 ‘신들린’ 기능을 모두 해결합니다.\n개정 문구: <b>강제</b> - 당신이 부착된 장소에서 '나간 후': 그 장소의 ‘신들린’ 기능을 모두 해결합니다."
<b>강제</b> 기능의 전제 조건이 다음과 같이 수정되어야 합니다: 당신이 부착된 장소에서 나갈 때

2022-08-29 14:01 UTC, elkeinkrad commented on errata/ko/errata.json
> +          "text": "본 카드의 강제 기능이 게임 밸런스를 위해 수정되었습니다. 정오표는 금기 목록과는 다르게 선택 규칙이 아니며, 반드시 적용해야한다는 점을 참고하시길 바랍니다.\n기존 문구: <b>강제</b> - 당신이 이벤트 카드 1장을 플레이한 후: 그 카드를 당신의 버린 카드 더미 대신 당신의 덱 가장 아래에 놓습니다.\n개정 문구:
플레이어 카드는 삭제하거나, 사견은 다 제외하고 문구만 남겨주세요.

2022-08-29 14:01 UTC, elkeinkrad commented on faq/ko/investigator.json
> +    "text": "- **질문:** '모사'로 찾아서 소모한 카드는 임시로 조종권을 가져오나요? 혹은 소유자가 조종한 채로 소모하기만 하나요? **답변:** (*참고: “다른 조사자의 전용 카드는 '모사'로 소모할 수 없습니다” 문구는 FAQ 1.4에서 전용 카드의 조종 규칙이 개정되면서 다른 조사자의 전용 카드를 소모할 수 있게 되었습니다.) '모
다른 조사자의 전용 카드는 '모사'로 소모할 수 없습니다. 라는 문구 삭제 (html에서 참고용으로 취소선을 그었으니 여기서는 삭제하는게 옳아요)

2022-08-29 14:03 UTC, elkeinkrad commented on errata/ko/errata.json
> +          "text": "기존 문구: <b>강제</b> – ‘버질 그레이’가 '쓰러지면': ‘버질 그레이’를 게임에서 제거합니다.\n개정 문구: <b>강제</b> – ‘버질 그레이’가 '플레이 영역에서 나가면': ‘버질 그레이’를 게임에서 제거합니다."
깃허브 특성상 강제가 굵게 표현되어있는데 `<b>강제</b>`인거 체크해주세요~~

2022-08-29 14:04 UTC, elkeinkrad commented on errata/ko/errata.json
> +          "text": "기존 문구: <b>강제</b> – '라운드 끝에', ‘데이곤의 침소’에 조사자가 있고 ‘데이곤’이 준비 상태라면: 이 적에게 파멸을 1개 놓습니다.\n개정 문구: <b>강제</b> – '조사 단계 끝에', ‘데이곤의 침소’에 조사자가 있고 ‘데이곤’이 준비 상태라면: 이 적에게 파멸을 1개 놓습니다."
원하시면 `조사 단계 끝에, ‘데이곤의 침소’에 조사자가 있고 ‘데이곤’이 준비 상태라면` 같이 전부 적으셔도 됩니다!

2022-08-29 14:46 UTC, zzorba commented
Yes, that's right @elkeinkrad, ArkhamDB policy is to apply the errata of player + encounter cards directly to them.  The PR for the english errata will be merged shortly, but a PR for KO can be done at any time as well.  

We could create entries for them in ArkhamCards as well to surface the fact that they were errata-ed. 

I believe entries 1.23-1.26 2.13 etc should be added to the Rules.  I will add them to english rules today to give them a 'link' code, and they should be added in the appropriate section to the korean rules translations.

2022-08-29 15:08 UTC, zzorba commented
I added the new FAQ entries to the english rules here (this is where DTTF chose to put the new FAQ entries structure wise) https://github.com/zzorba/arkham-cards-data/commit/8baf2b6d2d8ac6d4d48c3b88f20abbae71241c9a

2022-08-30 07:18 UTC, elkeinkrad requested changes
I think that `id` of the translation part should be match, and the item with id which does not exist at the english version may not be expressed onto the app.

I checked some parts and find the right place in the review; However, I cannot find the place of the FAQ 1.21 (Being at No Location).

---
To @derornos: 

`id` 부분은 매치가 되야 앱에서 반영이 될 것으로 보입니다. 그리하여 전부는 아니지만 FAQ 부분에 대해서 검색해보고 없는 것들은 영문 기준으로 찾아서 위치를 적어두었어요. 해당 위치로 옮기시면 될거같아요. 다만 FAQ 1.21은 제가 찾지 못하였습니다 ㅎㅎ;

2022-08-30 07:18 UTC, elkeinkrad commented on rules/ko/rules.json
> +    "title": " 타로 슬롯",
title 앞에 띄어쓰기가 있는 친구들이 있는데, 번거롭더라도 `" `로 검색해서 삭제하시는게 좋을거 같아요.

정규식 검색이 되면 `" [가-힣]`으로 검색하셔도 좋을듯 싶습니다. 전체적인 현상이므로 한번 훓으시는게 좋겠어요.

2022-08-30 07:18 UTC, elkeinkrad commented on rules/ko/rules.json
> +    "title": " (1.3) 반응([reaction]) 기회",
영문 기준으로 FAQ 숫자는 기재하고 있지 않은데, 한글은 기재하는게 나을까요? 아무래도 RR에 추가기재되는 부분이다 보니까 없는게 이쁘지 않을까도 싶습니다.

2022-08-30 07:18 UTC, elkeinkrad commented on rules/ko/rules.json
> +    "id": "Being_at_No_Location",
rules/en/rules.json 에 해당 id가 없는거 같은데 확인 필요

2022-08-30 07:18 UTC, elkeinkrad commented on rules/ko/rules.json
> +    "text": "카드의 효과를 통해서는 비어있는 플레이어 덱이나 조우 덱에 카드 단 1장만을 섞어넣을 수는 없습니다. 이 카드 섞기가 발생한 상황에 따라서 해결 방법이 달라집니다:\n- 카드 플레이/카드의 폭로 기능 해결 동안 발생한 경우(대개 이벤트나 음모처럼 해결한 후 버리는 카드): 해결이 끝난 후, 그 카드를 섞어넣지 않고 버립니다.\n-
이 항목은 Discard_Piles 에 병합되어 있으니 확인후 추가하시면 좋겠습니다.

2022-08-30 07:18 UTC, elkeinkrad commented on rules/ko/rules.json
> +    "text": "어떤 효과가 조사자로 하여금 치워두었던 카드를 가져와서 조종하라고 지시하는 경우, 지시된 카드를 가져와서 해당 조사자의 플레이 영역에 둡니다."
Set_Aside 에 같이 있으니 병합 필요

2022-08-30 07:18 UTC, elkeinkrad commented on rules/ko/rules.json
> +    "title": " (2.8) 보유한 자원 개수",
Resources에 같이 있으니 병합 필요

2022-08-30 14:38 UTC, zzorba commented
It is actually okay to have new 'ID' entries that only exist in the Korean language.  The only reason to keep the ID consistent (where possible) is it allows me to hyperlink from arkhamdb rules on FAQ/Comments into the native rules experience.  But adding your own entries for Korean FAQ entries is totally fine.

2022-08-30 15:29 UTC, derornos commented on rules/ko/rules.json
> +    "title": " 타로 슬롯",
일부러 그렇게 한거라 괜찮아요. 참조 안내서 부분에 있는 거랑 없는 거랑 차이를 두기 위해서 그렇게 조치하였습니다. (딜럭스 안내서 맨 앞 장에 나온 추가 규칙 같은게 대부분입니다.)
마찬가지 이유로 규칙 보충 해설 파트에 있는 것들의 타이틀 앞에도 띄어쓰기가 있습니다.

2022-08-30 15:31 UTC, derornos commented on rules/ko/rules.json
> +    "title": " (1.3) 반응([reaction]) 기회",
고민을 하다가 넣었습니다.
규칙 보충 해설 파트의 일부는 따로 메뉴가 있는게 아니라,
참조 안내서 내용에 추가를 해놓으신게 있더라구요...
그래서 검색하거나 관리할때 좀 불편해서 추가를 해보았습니다.

2022-08-30 15:32 UTC, derornos commented on rules/ko/rules.json
> +    "id": "Being_at_No_Location",
언어별 rules.json 마다 다른 세트를 사용하고 있는 것 같아서 추가한 내용입니다.
실제로 순서나 id, 제목 등이 영판에 있거나 동일한지 등을 체크하지는 않는 것 같더라구요.

2022-08-30 15:36 UTC, derornos commented on rules/ko/rules.json
> +    "text": "카드의 효과를 통해서는 비어있는 플레이어 덱이나 조우 덱에 카드 단 1장만을 섞어넣을 수는 없습니다. 이 카드 섞기가 발생한 상황에 따라서 해결 방법이 달라집니다:\n- 카드 플레이/카드의 폭로 기능 해결 동안 발생한 경우(대개 이벤트나 음모처럼 해결한 후 버리는 카드): 해결이 끝난 후, 그 카드를 섞어넣지 않고 버립니다.\n-
넵넵. 해당 영역에 병합되어 있긴 한데, 아컴 허브에 있는 내용이 어딘가에는 포함되어 있어야 한다는 생각이 들어서 추가한 내용입니다. 1.13 내용 중 일부를 검색했을 때, 나오긴 해야할 거 같아서요 ㅎㅎ

2022-08-30 15:37 UTC, derornos commented on rules/ko/rules.json
> +    "text": "어떤 효과가 조사자로 하여금 치워두었던 카드를 가져와서 조종하라고 지시하는 경우, 지시된 카드를 가져와서 해당 조사자의 플레이 영역에 둡니다."
위와 같은 이유로 추가한 내용입니다 : )

2022-08-30 15:37 UTC, derornos commented on rules/ko/rules.json
> +    "title": " (2.8) 보유한 자원 개수",
위와 같은 이유로 추가한 내용입니다 : )

2022-08-30 15:45 UTC, derornos commented
maybe... done...
: )

thanks, @zzorba @elkeinkrad

2022-08-30 18:35 UTC, zzorba commented
Awesome, I'll merge this -- we can always edit it further in a new PR.

2022-08-30 18:35 UTC, merged